import type { Work, Section } from "@/lib/types";

export const siteConfig = {
  name: "牟怡夫",
  nameEn: "Mou Yifu",
  title: "Mou Yifu — 3D Character Artist Portfolio",
  description: "牟怡夫个人 CG 作品集 · 3D角色建模 / 写实雕刻 / 材质制作 · Game Art Portfolio",
  tagline: "3D Character / Realistic Sculpting / PBR Texturing",
  email: "justdoitxiaofu@gmail.com",
  phone: "13640555098",
  wechat: "justdoitxiaofu",
  city: "重庆",
  github: "https://github.com/yifumou",
  artstation: "https://www.artstation.com/yifumou",
};

export const introContent = `专注于3D角色建模与材质制作的CG艺术家
曾参与《鸣潮》《和平精英》《英雄无敌:上古纪元》等项目
擅长写实生物雕刻、次世代角色制作及PBR材质表现`;

export const works: Work[] = [
  {
    id: "work-01",
    title: "镇墓兽 · 写实生物雕刻",
    description: "传统文化与写实生物雕刻结合，高精度ZBrush雕刻作品，完整展示高模细节与贴图表现。",
    image_url: "/works/page_06.jpg",
    thumb_url: "/works/page_06.jpg",
    tags: ["写实雕刻", "生物"],
    software: ["ZBrush", "Substance Painter", "Marmoset"],
    work_date: "2024",
    pinned: true,
    image_size: 0,
    sort_order: 100,
    size_weight: 1.5,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    image_count: 2,
  },
  {
    id: "work-02",
    title: "雨蛙 · 写实生物雕刻",
    description: "高精度写实雨蛙雕刻，注重皮肤质感与微观细节的表现。",
    image_url: "/works/page_08.jpg",
    thumb_url: "/works/page_08.jpg",
    tags: ["写实雕刻", "生物"],
    software: ["ZBrush", "Substance Painter"],
    work_date: "2024",
    pinned: true,
    image_size: 0,
    sort_order: 95,
    size_weight: 1.0,
    created_at: "2024-01-02",
    updated_at: "2024-01-02",
    image_count: 1,
  },
  {
    id: "work-03",
    title: "唐三彩兽形佛塔刹",
    description: "传统文化主题作品，唐三彩风格兽形佛塔刹雕刻与材质还原。",
    image_url: "/works/page_10.jpg",
    thumb_url: "/works/page_10.jpg",
    tags: ["传统文化", "道具"],
    software: ["ZBrush", "Substance Painter", "Maya"],
    work_date: "2024",
    pinned: true,
    image_size: 0,
    sort_order: 90,
    size_weight: 1.2,
    created_at: "2024-01-03",
    updated_at: "2024-01-03",
    image_count: 1,
  },
  {
    id: "work-04",
    title: "龙纹武器 · 逆水寒风格",
    description: "逆水寒风格龙纹武器道具制作，融合中国传统纹样与仙侠美学。",
    image_url: "/works/page_15.jpg",
    thumb_url: "/works/page_15.jpg",
    tags: ["武器道具", "仙侠风格"],
    software: ["Maya", "Substance Painter", "Marmoset"],
    work_date: "2024",
    pinned: false,
    image_size: 0,
    sort_order: 85,
    size_weight: 1.0,
    created_at: "2024-01-04",
    updated_at: "2024-01-04",
    image_count: 1,
  },
  {
    id: "work-05",
    title: "次世代军事角色",
    description: "次世代军事风格全身角色，完整展示高模、低模、贴图制作流程。",
    image_url: "/works/page_20.jpg",
    thumb_url: "/works/page_20.jpg",
    tags: ["次世代角色", "写实"],
    software: ["ZBrush", "Maya", "Substance Painter", "Marmoset"],
    work_date: "2024",
    pinned: true,
    image_size: 0,
    sort_order: 80,
    size_weight: 1.5,
    created_at: "2024-01-05",
    updated_at: "2024-01-05",
    image_count: 1,
  },
  {
    id: "work-06",
    title: "鸣潮 · 库洛科技项目作品",
    description: "参与库洛科技《鸣潮》3.0-3.2版本角色建模与材质制作。",
    image_url: "/works/page_04.jpg",
    thumb_url: "/works/page_04.jpg",
    tags: ["项目经历", "角色"],
    software: ["Maya", "ZBrush", "Substance Painter"],
    work_date: "2025",
    pinned: true,
    image_size: 0,
    sort_order: 110,
    size_weight: 1.5,
    created_at: "2025-01-01",
    updated_at: "2025-01-01",
    image_count: 1,
  },
  {
    id: "work-07",
    title: "和平精英 · BOSS套装",
    description: "腾讯光子工作室《和平精英》BOSS套装角色建模。",
    image_url: "/works/page_03.jpg",
    thumb_url: "/works/page_03.jpg",
    tags: ["项目经历", "角色"],
    software: ["Maya", "ZBrush", "Substance Painter"],
    work_date: "2024",
    pinned: false,
    image_size: 0,
    sort_order: 75,
    size_weight: 1.2,
    created_at: "2024-01-06",
    updated_at: "2024-01-06",
    image_count: 1,
  },
  {
    id: "work-08",
    title: "英雄无敌:上古纪元 · 蛇鲨科技",
    description: "蛇鲨科技（育碧）《英雄无敌:上古纪元》项目角色制作。",
    image_url: "/works/page_02.jpg",
    thumb_url: "/works/page_02.jpg",
    tags: ["项目经历", "角色"],
    software: ["Maya", "ZBrush", "Substance Painter"],
    work_date: "2024",
    pinned: false,
    image_size: 0,
    sort_order: 70,
    size_weight: 1.0,
    created_at: "2024-01-07",
    updated_at: "2024-01-07",
    image_count: 1,
  },
];

// 更多作品 - 从剩余页面补充
export const additionalWorks: Work[] = [
  {
    id: "work-09",
    title: "镇墓兽 · 贴图展示",
    description: "镇墓兽完整贴图流程与材质球展示。",
    image_url: "/works/page_07.jpg",
    thumb_url: "/works/page_07.jpg",
    tags: ["写实雕刻", "材质"],
    software: ["Substance Painter", "Marmoset"],
    work_date: "2024",
    pinned: false,
    image_size: 0,
    sort_order: 65,
    size_weight: 1.0,
    created_at: "2024-01-08",
    updated_at: "2024-01-08",
    image_count: 1,
  },
  {
    id: "work-10",
    title: "个人作品集 · 更多展示",
    description: "更多角色、道具与材质作品合集。",
    image_url: "/works/page_09.jpg",
    thumb_url: "/works/page_09.jpg",
    tags: ["作品集"],
    software: ["ZBrush", "Maya", "Substance Painter"],
    work_date: "2024",
    pinned: false,
    image_size: 0,
    sort_order: 60,
    size_weight: 1.0,
    created_at: "2024-01-09",
    updated_at: "2024-01-09",
    image_count: 1,
  },
];

export const allWorks: Work[] = [...works, ...additionalWorks];

export const detailSections: Section[] = [
  {
    id: "section-1",
    title: "工作经历",
    content: `**库洛科技** — 《鸣潮》3D角色建模师 (3.0-3.2版本)
**蛇鲨科技（育碧）** — 《英雄无敌:上古纪元》角色制作
**腾讯光子工作室** — 《和平精英》BOSS套装角色建模`,
  },
  {
    id: "section-2",
    title: "学习经历",
    content: `**腾讯 OpenLight 训练营** — 3D美术方向
**网易逆水寒训练营** — 武器道具建模
**魔型志** — 角色建模系统学习
**黄惠峰培训班** — 高级角色建模
**Hafez Yadollahi** — AAA角色创建课程`,
  },
  {
    id: "section-3",
    title: "教育背景",
    content: `**重庆文化艺术职业学院** — 游戏艺术设计专业 (2023-2026)`,
  },
  {
    id: "section-4",
    title: "专业技能",
    content: `**建模软件：** ZBrush / Maya / Blender / 3ds Max
**材质贴图：** Substance Painter / Substance Designer / Mari
**渲染引擎：** Marmoset Toolbag / V-Ray / Arnold
**游戏引擎：** Unreal Engine 5 / Unity
**其他工具：** Photoshop / Illustrator / RizomUV`,
  },
];
